package com.anatame.pickaflix.common.utils

data class BlockHosts(
    val hosts2: List<String> = listOf<String>(
        "www.googletagmanager.com",
        "g.jwpsrv.com"

    ),
    val hosts: List<String> = listOf<String>(
        "absolutionbravery.com",
        "addthis.com",
        "s7.addthis.com",
        "amung.us",
        "whos.amung.us",
        "onesignal.com",
        "cdn.onesignal.com",
        "xmllover.com",
        "googletagmanager.com",
        "www.googletagmanager.com",
        "google-analytics.com",
        "www.google-analytics.com",
        "connect.facebook.net",
        "disqus.com",
        "referrer.disqus.com",
        "offerimage.com",
   //     "s1.bunnycdn.ru",
        "dacmaiss.com",
        "s7.addthis.com",
        "zap.buzz",
        "s7.addthis.com",
        "addresseepaper.com",
        "venetrigni.com",
        "portserratic.com",
        "offerimage.com",
        "regulationprivilegescan.top",
        "disqus.com",
        "fonts.googleapis.com",
        "use.fontawesome.com",
        "ytube2dl.com",
        "dismantlepenantiterrorist.com",
        "venetrigni.com",
        "cdnjs.cloudflare.com",
        "offerimage.com",
        "rndskittytor.com",
        "applive.co.in",
        "static.cloudflareinsights.com",
        "res.cloudinary.com",
        "in.cmproclean.club",
        "www.google-analytics.com",
//    "cdn.heycdn41.xyz",
        "     cdn.trell.co",
//        "www.gstatic.com",
        "untimburra.com",
        //      "ssl.p.jwpcdn.com",
        "i.imgur.com",
    )
)
